// <auto-generated />
using System;
using Clinic.Infrastructure.Sqlserver.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinic.Infrastructure.Sqlserver.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260817071524_AddQueueCounterTable")]
    partial class AddQueueCounterTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clinic.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWalkIn")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TimeSlot")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Qualification")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.MedicalReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ExamEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExamStartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Prescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("QueueTicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QueueTicketId")
                        .IsUnique();

                    b.ToTable("MedicalReports", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SendTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InsuranceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create appointments",
                            IsDeleted = false,
                            Name = "appointment.create"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View appointments",
                            IsDeleted = false,
                            Name = "appointment.view"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cancel appointments (deprecated - dùng appointment.cancel.own/.any)",
                            IsDeleted = true,
                            Name = "appointment.cancel"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000e"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cancel own appointment (Patient)",
                            IsDeleted = false,
                            Name = "appointment.cancel.own"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cancel any appointment (Admin/Receptionist)",
                            IsDeleted = false,
                            Name = "appointment.cancel.any"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Call next in queue",
                            IsDeleted = false,
                            Name = "queue.call-next"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View doctor profile",
                            IsDeleted = false,
                            Name = "doctor.view"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edit doctor profile (deprecated - dùng doctor.edit.own/.any)",
                            IsDeleted = true,
                            Name = "doctor.edit"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage users",
                            IsDeleted = false,
                            Name = "user.manage"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage roles and permissions",
                            IsDeleted = false,
                            Name = "role.manage"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Update appointments",
                            IsDeleted = false,
                            Name = "appointment.update"
                        },
                        new
                        {
                            Id = new Guid("1000000a-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Confirm appointments",
                            IsDeleted = false,
                            Name = "appointment.confirm"
                        },
                        new
                        {
                            Id = new Guid("1000000a-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reschedule appointments",
                            IsDeleted = false,
                            Name = "appointment.reschedule"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View doctor's queue",
                            IsDeleted = false,
                            Name = "doctor.queue.view"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000d"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create doctor profile",
                            IsDeleted = false,
                            Name = "doctor.create"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edit own doctor profile (Doctor)",
                            IsDeleted = false,
                            Name = "doctor.edit.own"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edit any doctor profile (Admin)",
                            IsDeleted = false,
                            Name = "doctor.edit.any"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View medical reports",
                            IsDeleted = true,
                            Name = "medical-report.view"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create medical reports",
                            IsDeleted = false,
                            Name = "medical-report.create"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View patient medical history",
                            IsDeleted = true,
                            Name = "patient-history.view"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage any doctor's shifts",
                            IsDeleted = false,
                            Name = "shift.manage"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage own shift requests",
                            IsDeleted = false,
                            Name = "shift.self-manage"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View queue",
                            IsDeleted = false,
                            Name = "queue.view"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Check in a patient into queue",
                            IsDeleted = false,
                            Name = "queue.check-in"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Skip a patient in queue",
                            IsDeleted = false,
                            Name = "queue.skip"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Set priority in queue",
                            IsDeleted = false,
                            Name = "queue.priority"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View own medical reports (Patient)",
                            IsDeleted = false,
                            Name = "medical-report.view.own"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View medical reports of patients in own exam cases (Doctor)",
                            IsDeleted = false,
                            Name = "medical-report.view.related"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View any medical report (Admin)",
                            IsDeleted = false,
                            Name = "medical-report.view.any"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000d"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View own medical history (Patient)",
                            IsDeleted = false,
                            Name = "patient-history.view.own"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000e"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View medical history of patients in own exam cases (Doctor)",
                            IsDeleted = false,
                            Name = "patient-history.view.related"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View any patient's medical history (Admin)",
                            IsDeleted = false,
                            Name = "patient-history.view.any"
                        },
                        new
                        {
                            Id = new Guid("2000000a-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage notifications",
                            IsDeleted = false,
                            Name = "notification.manage"
                        },
                        new
                        {
                            Id = new Guid("2000000a-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View clinic-wide reports",
                            IsDeleted = false,
                            Name = "report.view"
                        },
                        new
                        {
                            Id = new Guid("2000000a-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage medical specialties",
                            IsDeleted = false,
                            Name = "specialty.manage"
                        },
                        new
                        {
                            Id = new Guid("2000000a-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View appointment slots",
                            IsDeleted = false,
                            Name = "slot.view"
                        },
                        new
                        {
                            Id = new Guid("2000000a-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage appointment slots",
                            IsDeleted = false,
                            Name = "slot.manage"
                        },
                        new
                        {
                            Id = new Guid("2000000a-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Approve/reject doctor shift-change suggestions (Receptionist)",
                            IsDeleted = false,
                            Name = "shift.suggestion.manage"
                        });
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.QueueCounter", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("CurrentNumber")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "Date");

                    b.ToTable("QueueCounters", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.QueueTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Priority")
                        .HasColumnType("bit");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("QueueTickets", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Administrator role",
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Patient role",
                            IsDeleted = false,
                            Name = "Patient"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Receptionist role",
                            IsDeleted = false,
                            Name = "Receptionist"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Doctor role",
                            IsDeleted = false,
                            Name = "Doctor"
                        });
                });

            modelBuilder.Entity("Clinic.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("2000000a-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("2000000a-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("2000000a-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("2000000a-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("2000000a-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("1000000a-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("2000000a-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("2000000a-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("2000000a-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("2000000a-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("20000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("20000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("2000000a-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("1000000a-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("20000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("2000000a-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("Clinic.Domain.Entities.ShiftRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ShiftEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("ShiftRequests", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("EstablishedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Specialties", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.WorkHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("WorkHistories", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientLimitPerSlot")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("WorkSchedules", (string)null);
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.WorkSchedule", "WorkSchedule")
                        .WithMany("Appointments")
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Employee", "Employee")
                        .WithOne("Doctor")
                        .HasForeignKey("Clinic.Domain.Entities.Doctor", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinic.Domain.Entities.Person", "Person")
                        .WithOne("Employee")
                        .HasForeignKey("Clinic.Domain.Entities.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.MedicalReport", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.QueueTicket", "QueueTicket")
                        .WithOne("MedicalReport")
                        .HasForeignKey("Clinic.Domain.Entities.MedicalReport", "QueueTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QueueTicket");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Person", "Person")
                        .WithMany("Notifications")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Patient", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Person", "Person")
                        .WithOne("Patient")
                        .HasForeignKey("Clinic.Domain.Entities.Patient", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.QueueTicket", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Appointment", "Appointment")
                        .WithOne("QueueTicket")
                        .HasForeignKey("Clinic.Domain.Entities.QueueTicket", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.ShiftRequest", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Doctor", "Doctor")
                        .WithMany("ShiftRequests")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.User", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("Clinic.Domain.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.WorkHistory", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Doctor", "Doctor")
                        .WithMany("WorkHistories")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Domain.Entities.Specialty", "Specialty")
                        .WithMany("WorkHistories")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("Clinic.Domain.Entities.Doctor", "Doctor")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("QueueTicket");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("ShiftRequests");

                    b.Navigation("WorkHistories");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Person", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("Notifications");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.QueueTicket", b =>
                {
                    b.Navigation("MedicalReport");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("WorkHistories");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Clinic.Domain.Entities.WorkSchedule", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
