<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ApiError } from '@/lib/api/http'
import { doctorsApi } from '@/features/doctors/doctors.api'
import type { DoctorSchedule, RequestedShift } from '@/features/doctors/doctors.types'

function isoDate(date: Date) { return date.toISOString().slice(0, 10) }
const now = new Date(); const end = new Date(now); end.setDate(end.getDate() + 30)
const startDate = ref(isoDate(now)); const endDate = ref(isoDate(end))
const data = ref<DoctorSchedule<RequestedShift> | null>(null)
const loading = ref(false); const saving = ref(false); const error = ref(''); const notice = ref('')
const editingId = ref<string | null>(null)
const form = reactive({ date: isoDate(now), startTime: '08:00', endTime: '12:00', patientLimit: 20, reason: '' })
function msg(e: unknown) { return e instanceof ApiError ? e.message : e instanceof Error ? e.message : 'Có lỗi xảy ra.' }
function reset() { editingId.value = null; form.date = isoDate(now); form.startTime = '08:00'; form.endTime = '12:00'; form.patientLimit = 20; form.reason = '' }
async function load() { loading.value = true; error.value = ''; try { data.value = await doctorsApi.getOwnShiftRequests(startDate.value, endDate.value) } catch (e) { error.value = msg(e) } finally { loading.value = false } }
function edit(item: RequestedShift) { editingId.value = item.id; form.date = item.date; form.startTime = item.startTime.slice(0,5); form.endTime = item.endTime.slice(0,5); form.patientLimit = item.patientLimit; form.reason = item.reason ?? ''; window.scrollTo({ top: 0, behavior: 'smooth' }) }
async function submit() { saving.value = true; error.value = ''; notice.value = ''; try { if (editingId.value) { await doctorsApi.updateShiftRequest(editingId.value, { date: form.date, startTime: form.startTime, endTime: form.endTime, patientLimitPerSlot: Number(form.patientLimit), reason: form.reason }) } else { await doctorsApi.createShiftRequest({ date: form.date, startTime: form.startTime, endTime: form.endTime, patientLimit: Number(form.patientLimit), reason: form.reason }) }; notice.value = editingId.value ? 'Đã cập nhật yêu cầu.' : 'Đã gửi yêu cầu ca làm việc.'; reset(); await load() } catch (e) { error.value = msg(e) } finally { saving.value = false } }
async function cancel(item: RequestedShift) { if (!confirm('Huỷ yêu cầu ca này?')) return; saving.value = true; try { await doctorsApi.cancelShiftRequest(item.id); notice.value = 'Đã huỷ yêu cầu.'; await load() } catch (e) { error.value = msg(e) } finally { saving.value = false } }
function statusClass(status: string) { return ({ Pending: 'bg-amber-50 text-amber-700', Approved: 'bg-emerald-50 text-emerald-700', Rejected: 'bg-red-50 text-red-700', Cancelled: 'bg-slate-100 text-slate-600' } as Record<string,string>)[status] ?? 'bg-slate-100 text-slate-600' }
onMounted(load)
</script>

<template>
  <div class="space-y-6">
    <div><p class="text-sm font-medium text-violet-600">Bác sĩ</p><h1 class="text-2xl font-bold text-slate-900">Đề xuất ca làm việc</h1><p class="mt-1 text-sm text-slate-500">Bác sĩ gửi yêu cầu; quản trị viên sẽ phê duyệt hoặc từ chối.</p></div>
    <div v-if="error" class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ error }}</div><div v-if="notice" class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{{ notice }}</div>
    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">{{ editingId ? 'Chỉnh sửa yêu cầu' : 'Tạo yêu cầu mới' }}</h2><form class="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-5" @submit.prevent="submit"><label class="text-sm">Ngày<input v-model="form.date" type="date" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"></label><label class="text-sm">Bắt đầu<input v-model="form.startTime" type="time" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"></label><label class="text-sm">Kết thúc<input v-model="form.endTime" type="time" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"></label><label class="text-sm">Giới hạn bệnh nhân<input v-model.number="form.patientLimit" type="number" min="1" max="50" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"></label><label class="text-sm md:col-span-2 lg:col-span-1">Lý do<input v-model="form.reason" type="text" required placeholder="Ví dụ: tăng ca" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"></label><div class="flex items-end gap-2 lg:col-span-5"><button class="rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50" :disabled="saving">{{ editingId ? 'Lưu thay đổi' : 'Gửi yêu cầu' }}</button><button v-if="editingId" type="button" class="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold" @click="reset">Huỷ sửa</button></div></form></section>
    <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex flex-wrap items-end justify-between gap-3 border-b border-slate-100 p-5"><div><h2 class="font-semibold">Lịch sử yêu cầu</h2><p class="text-sm text-slate-500">{{ data?.schedules.length ?? 0 }} yêu cầu</p></div><div class="flex gap-2"><input v-model="startDate" type="date" class="rounded-lg border border-slate-200 px-3 py-2 text-sm"><input v-model="endDate" type="date" class="rounded-lg border border-slate-200 px-3 py-2 text-sm"><button class="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold" @click="load">Lọc</button></div></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Ngày</th><th class="px-5 py-3">Giờ</th><th class="px-5 py-3">Giới hạn</th><th class="px-5 py-3">Lý do</th><th class="px-5 py-3">Trạng thái</th><th class="px-5 py-3 text-right">Thao tác</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="item in data?.schedules" :key="item.id"><td class="px-5 py-4">{{ item.date }}</td><td class="px-5 py-4">{{ item.startTime.slice(0,5) }} – {{ item.endTime.slice(0,5) }}</td><td class="px-5 py-4">{{ item.patientLimit }}</td><td class="max-w-64 px-5 py-4">{{ item.reason || '—' }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="statusClass(item.status)">{{ item.status }}</span></td><td class="px-5 py-4 text-right"><div class="flex justify-end gap-2" v-if="['Pending'].includes(item.status)"><button class="rounded-md border border-slate-200 px-3 py-1.5 text-xs font-semibold" :disabled="saving" @click="edit(item)">Sửa</button><button class="rounded-md border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-600" :disabled="saving" @click="cancel(item)">Huỷ</button></div></td></tr><tr v-if="!loading && !data?.schedules.length"><td colspan="6" class="px-5 py-12 text-center text-slate-500">Chưa có yêu cầu.</td></tr></tbody></table></div></section>
  </div>
</template>
