import type {
  Doctor,
  QueueItem,
  RecentCheckin,
} from './receptionist.types'

export const DOCTORS: Doctor[] = [
  {
    id: 1,
    name: 'BS. Nguyễn Thị Hương',
    specialty: 'Nội tổng quát',
    room: 'P.101',
    prefix: 'A',
    color: 'blue',
  },
  {
    id: 2,
    name: 'BS. Trần Minh Khoa',
    specialty: 'Tim mạch',
    room: 'P.202',
    prefix: 'B',
    color: 'violet',
  },
  {
    id: 3,
    name: 'BS. Lê Thị Lan',
    specialty: 'Nhi khoa',
    room: 'P.303',
    prefix: 'C',
    color: 'emerald',
  },
]

export const INIT_QUEUE: QueueItem[] = [
  {
    ticket: 'A001',
    name: 'Nguyễn Văn An',
    docId: 1,
    time: '08:00',
    status: 'in-progress',
    wait: 0,
    urgent: false,
  },
  {
    ticket: 'A002',
    name: 'Trần Thị Bích',
    docId: 1,
    time: '08:30',
    status: 'waiting',
    wait: 14,
    urgent: false,
  },
  {
    ticket: 'A003',
    name: 'Lê Minh Đức',
    docId: 1,
    time: '09:30',
    status: 'waiting',
    wait: 32,
    urgent: true,
  },
  {
    ticket: 'A004',
    name: 'Phạm Thị Dung',
    docId: 1,
    time: '10:00',
    status: 'waiting',
    wait: 47,
    urgent: false,
  },
  {
    ticket: 'B001',
    name: 'Hoàng Văn Phi',
    docId: 2,
    time: '09:30',
    status: 'in-progress',
    wait: 0,
    urgent: false,
  },
  {
    ticket: 'B002',
    name: 'Võ Thị Giang',
    docId: 2,
    time: '10:00',
    status: 'waiting',
    wait: 18,
    urgent: false,
  },
  {
    ticket: 'B003',
    name: 'Đặng Minh Hà',
    docId: 2,
    time: '10:30',
    status: 'waiting',
    wait: 35,
    urgent: true,
  },
  {
    ticket: 'C001',
    name: 'Bùi Thị Hoa',
    docId: 3,
    time: '08:00',
    status: 'completed',
    wait: 0,
    urgent: false,
  },
  {
    ticket: 'C002',
    name: 'Phan Văn Hùng',
    docId: 3,
    time: '09:00',
    status: 'in-progress',
    wait: 0,
    urgent: false,
  },
  {
    ticket: 'C003',
    name: 'Lý Thị Lan',
    docId: 3,
    time: '14:00',
    status: 'waiting',
    wait: 22,
    urgent: false,
  },
]

export const RECENT_CHECKINS: RecentCheckin[] = [
  {
    ticket: 'C003',
    name: 'Lý Thị Lan',
    doc: 'BS. Lê Thị Lan',
    time: '09:15',
  },
  {
    ticket: 'B003',
    name: 'Đặng Minh Hà',
    doc: 'BS. Trần Minh Khoa',
    time: '09:08',
  },
  {
    ticket: 'A004',
    name: 'Phạm Thị Dung',
    doc: 'BS. Nguyễn Thị Hương',
    time: '08:52',
  },
]
